spring.application.name=OnlineRecruitment

# ============ DATASOURCE ============
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineRecruitment;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============ JPA / HIBERNATE ============
# DB đã tạo bằng SQL script → KHÔNG cho Hibernate sửa cấu trúc
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ============ THYMELEAF ============
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ============ LOGGING ============
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE