spring.application.name=OnlineRecruitment
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineRecruitment;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# --- Gửi mail (Gmail). KHÔNG ghi mật khẩu thẳng vào file, dùng biến môi trường ---
# ===============================
# MAIL - GMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# ===============================
# OTP
# ===============================
app.otp.ttl-minutes=5
app.otp.resend-cooldown-seconds=60
app.otp.max-attempts=5
# Khi true: nếu Gmail chưa cấu hình,
# OTP sẽ được in trong Console để test.
app.otp.log-to-console=true
server.port=8082
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

app.upload.dir=uploads/cv


logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.web.FilterChainProxy=TRACE
server.servlet.session.tracking-modes=cookie

