spring.application.name=OnlineRecruitment

# Kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineRecruitment;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cấu hình Gmail SMTP để gửi OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${DB_PASSWORD}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# URL gốc dùng để sinh link xác thực gửi qua Email
app.base-url=http://localhost:8080